Repository 0dytpq0/final-project-b1, pull requests merged in 2024-07, with the labels that each got.

#23 feat : #14 destinationAPI
  src/apis/api.ts
  src/apis/area.api.ts
  src/apis/city.api.ts
  src/apis/country.api.ts
  src/apis/index.ts
  src/app/(provider)/(root)/destination/country/page.tsx
  src/app/api/area/[id]/route.ts
  src/app/api/area/route.ts
  src/app/api/area/search/route.ts
  src/app/api/city/[id]/route.ts
  src/app/api/city/route.ts
  src/app/api/city/search/route.ts
  src/app/api/country/[id]/route.ts
  src/app/api/country/route.ts
  src/app/api/country/search/route.ts
  src/components/Card/CardForm.tsx
  src/supabase/client.ts
  src/supabase/server.ts
Labels: 📌 feat

#34 Feat: #7 이메일 회원가입/로그인
  public/icon/login/password-eye-crossed.svg
  public/icon/login/password-eye.svg
  src/apis/api.ts
  src/apis/auth.api.ts
  src/app/(provider)/(root)/(auth)/login/_components/AuthForm/AuthForm.tsx
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/(auth)/login/layout.tsx
  src/app/(provider)/(root)/(auth)/login/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/auth/user/route.ts
  src/hooks/useAuthFlow.ts
  src/stores/auth.store.ts
  src/utils/emailCheck.ts
Labels: 📌 feat

#35 Feat : #33 area detail page layout
  public/icon/clean.png
  public/icon/cool.png
  public/icon/delicious.png
  public/icon/edit.svg
  src/apis/area.api.ts
  src/app/(provider)/(root)/recommend/_components/RecommendFormItem.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/app/(provider)/(root)/recommend/page.tsx
  src/app/api/area/bookmark/route.ts
  src/app/api/area/rating/route.ts
  src/components/Card/ImageContainer.tsx
  src/components/Card/RatingIcons.tsx
  src/components/Tab/Tab.tsx
  src/hooks/index.ts
  src/hooks/useTab.tsx
  src/stores/recommend.store.ts
  src/types/Recommend.ts
  src/utils/calcRatings.ts
Labels: 📌 feat, 🎉 add

#30 Feat: common components 및 Header 구현
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  public/icons/arrow-back-black.png
  public/icons/arrow-back-white.png
  public/icons/arrow-down-black.png
  public/icons/arrow-up-black.png
  public/icons/avatar-black.png
  public/icons/avatar-gray.png
  public/icons/cancel-black.png
  public/icons/chevron-blue.png
  public/icons/dotted-square-blue.png
  public/icons/edit-black.png
  public/icons/edit-blue.png
  public/icons/ellipsis-vertical-black.png
  public/icons/home-black.png
  public/icons/list-black.png
  public/icons/map-black.png
  public/icons/menu-burger-black.png
  public/icons/menu-burger-white.png
  public/icons/notification-black.png
  public/icons/search-black.png
  public/icons/search-white.png
  public/icons/settings-black.png
  public/sampleImg.jpg
  src/app/(provider)/(root)/_component/Home.tsx
  src/app/(provider)/(root)/commons-test/_component/TestComponent.tsx
  src/app/(provider)/(root)/commons-test/page.tsx
  src/app/(provider)/(root)/page.tsx
  src/app/layout.tsx
  src/components/CountryButton/CountryButton.stories.ts
  src/components/CountryButton/CountryButton.tsx
  src/components/CountryButton/index.ts
  src/components/Drawer/Category.tsx
  src/components/Drawer/ClientDrawer.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Layout/MainLayout.tsx
  src/components/commons/Header/Header.tsx
  src/components/commons/Header/index.ts
  src/components/commons/Icon/Icon.stories.ts
  src/components/commons/Icon/Icon.tsx
  src/components/commons/Icon/index.ts
  src/components/commons/Label/Label.tsx
  src/components/commons/Label/index.ts
  src/components/commons/SubmitButton/SubmitButton.stories.ts
  src/components/commons/SubmitButton/SubmitButton.tsx
  src/components/commons/SubmitButton/index.ts
  src/components/commons/TagButton/TagButton.stories.tsx
  src/components/commons/TagButton/TagButton.tsx
  src/components/commons/TagButton/index.ts
  src/constants/Icon.ts
  src/stores/useDrawerStore.ts
  tailwind.config.ts
Labels: 📌 feat

#58 Feat: search page ui 작업
  public/icons/filter-black.png
  public/icons/microphone-black.png
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/(auth)/login/layout.tsx
  src/app/(provider)/(root)/_component/Home.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/InitialSearchView.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/(provider)/(root)/search/layout.tsx
  src/app/(provider)/(root)/search/page.tsx
  src/components/Drawer/CategoryList.tsx
  src/components/SearchBar/SearchBar.tsx
  src/constants/Icon.ts
Labels: 📌 feat

#59 dev to main
  public/icons/filter-black.png
  public/icons/microphone-black.png
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/(auth)/login/layout.tsx
  src/app/(provider)/(root)/_component/Home.tsx
  src/app/(provider)/(root)/commons-test/_component/TestComponent.tsx
  src/app/(provider)/(root)/my-page/page.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/InitialSearchView.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/(provider)/(root)/search/layout.tsx
  src/app/(provider)/(root)/search/page.tsx
  src/app/globals.css
  src/components/CountryButton/CountryButton.tsx
  src/components/Drawer/Category.tsx
  src/components/Drawer/CategoryList.tsx
  src/components/Drawer/ClientDrawer.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/Menu.ts
  src/components/Drawer/MyTripPlanner.tsx
  src/components/Drawer/TripList.tsx
  src/components/Drawer/subCategory.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/commons/TagList/PrimaryTagList.tsx
  src/constants/Icon.ts
  src/constants/continents.ts
  src/stores/drawer.store.ts
Labels: 🚩end

#61 chore: [plan] 여행 경로 보여주기 #27
  package-lock.json
  package.json
  src/app/(provider)/(root)/plan/[planId]/route/_components/Map.tsx
  src/app/(provider)/(root)/plan/[planId]/route/page.tsx
  src/types/LatLng.ts
Labels: 🔧 chore

#62 feat: #7 소셜로그인 기능, 유저 데이터 저장 기능
  src/app/(provider)/(root)/(auth)/login/_components/AuthForm/AuthForm.tsx
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/(auth)/login/layout.tsx
  src/app/(provider)/(root)/(auth)/login/page.tsx
  src/app/(provider)/layout.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/signup/route.ts
  src/contexts/auth.contexts.tsx
  src/hooks/useAuthFlow.ts
  src/stores/auth.store.ts
  src/stores/path.store.ts
  src/stores/step.store.ts
Labels: ✨ update

#60 feat : #46 [나라, 관광지] 관광지 추천 관련 페이지 수정
  public/cardImages/bookmarked.png
  public/icons/cancel-white.png
  src/apis/api.ts
  src/apis/area.api.ts
  src/apis/bookmark.api.ts
  src/apis/review.api.ts
  src/app/(provider)/(root)/recommend/_components/AreaPage/AreaReviewCard.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/NoticeForm.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/UnderBar.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/_utils/checkIsBookmarked.ts
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/_components/Carousel/CarouselItem.tsx
  src/app/(provider)/(root)/recommend/_components/Carousel/CarouselList.tsx
  src/app/(provider)/(root)/recommend/_components/CountryPage/InstroSlider.tsx
  src/app/(provider)/(root)/recommend/_components/MainTour/MainTourForm.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/layout.tsx
  src/app/(provider)/(root)/recommend/country/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/app/(provider)/(root)/recommend/page.tsx
  src/app/api/area/[id]/route.ts
  src/app/api/bookmark/route.ts
  src/app/api/city/[id]/route.ts
  src/app/api/country/[id]/route.ts
  src/app/api/review/[id]/route.ts
  src/app/api/review/route.ts
  src/components/Carousel/Carousel.tsx
  src/components/Tab/Tab.tsx
  src/constants/Icon.ts
  src/hooks/useBookmark.ts
  src/types/Recommend.ts
  src/types/supabase.ts
  src/utils/calcRatings.ts
Labels: 📌 feat, ✨ update

#67 Feat: TagList 및 CardSlider 제작
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/_component/Home.tsx
  src/app/(provider)/(root)/commons-test/_component/TestComponent.tsx
  src/app/(provider)/(root)/commons-test/page.tsx
  src/app/(provider)/(root)/my-page/page.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheet.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetCheckList.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetImages.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetInput.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetTitle.tsx
  src/app/(provider)/(root)/plan/_components/TransportOption.tsx
  src/app/(provider)/(root)/plan/_components/UpdateButton.tsx
  src/app/(provider)/(root)/plan/layout.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/NoticeForm.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/layout.tsx
  src/app/(provider)/(root)/recommend/country/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/app/(provider)/(root)/search/layout.tsx
  src/app/api/plan/[planId]/schedule/route.ts
  src/components/Card/CardType.tsx
  src/components/Drawer/Category.tsx
  src/components/Drawer/CategoryList.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/TripList.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/Slider/CardSlider.tsx
  src/components/commons/Icon/Icon.stories.ts
  src/components/commons/TagButton/TagButton.tsx
  src/components/commons/TagList/PrimaryTagList.tsx
  src/components/commons/TagList/SlideTagList.tsx
  src/constants/icon.ts
  src/types/Slider.ts
  src/types/plan.ts
  src/types/supabase.ts
Labels: 📌 feat, 🔧 chore
