Repository 0dytpq0/final-project-b1, pull requests merged in 2024-08, with the labels that each got.

#74 dev to main
  src/apis/auth.api.ts
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/onboard/_components/OnBoard/OnBoard.tsx
  src/app/(provider)/(root)/onboard/_components/SelectButton/SelectButton.tsx
  src/app/(provider)/(root)/onboard/_components/SelectContainer/SelectContainer.tsx
  src/app/(provider)/(root)/onboard/_components/SelectForm/SelectForm.tsx
  src/app/(provider)/(root)/onboard/page.tsx
  src/app/api/auth/signup/route.ts
  src/middleware.ts
  src/stores/travelType.store.ts
Labels: 🚩end

#77 Feat: 검색 기능 구현 및 메인 페이지 UI 추가 작업
  public/banners/banner1_x1.png
  public/banners/banner1_x3.png
  public/icons/arrow-foward-lightgreen.png
  public/icons/cancel-gray.png
  src/apis/area.api.ts
  src/app/(provider)/(root)/_component/Home.tsx
  src/app/(provider)/(root)/_component/MyTrip.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/(provider)/(root)/search/layout.tsx
  src/app/(provider)/(root)/search/page.tsx
  src/app/api/area/search/route.ts
  src/components/CountryButton/CountryButton.tsx
  src/components/Drawer/Category.tsx
  src/components/Drawer/MyTripPlanner.tsx
  src/components/Drawer/TripList.tsx
  src/components/SearchBar/SearchBar.tsx
  src/constants/icon.ts
Labels: 📌 feat, ✨ update, 💄 style

#81 feat: #63 마이페이지 접근 redirect
  src/app/(provider)/(root)/(auth)/login/_components/AuthPage/AuthPage.tsx
  src/app/(provider)/(root)/(auth)/login/layout.tsx
  src/app/(provider)/(root)/_component/Home.tsx
  src/hooks/useAuthFlow.ts
  src/middleware.ts
Labels: ✨ update

#89 Feat: auto layout 조정
  public/banners/banner1_x3.png
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/_components/MyTrip.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/components/CountryButton/CountryButton.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/subCategory.ts
  src/components/SearchBar/SearchBar.tsx
  tailwind.config.ts
Labels: ✨ update, 🔧 chore

#109 마이페이지, 온보딩 이슈 해결 및 추가 기능
  next.config.mjs
  src/apis/auth.api.ts
  src/app/(provider)/(root)/my/_components/FooterList.tsx
  src/app/(provider)/(root)/my/_components/MyProfile.tsx
  src/app/(provider)/(root)/onboard/_components/OnBoard/OnBoard.tsx
  src/app/api/auth/logout/route.ts
  src/app/api/auth/update/route.ts
  src/app/api/auth/user/route.ts
  src/hooks/useAuthFlow.ts
  src/middleware.ts
Labels: 📌 feat, 🔧 chore

#110 Feat/96 main banner
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/(provider)/(root)/recommend/page.tsx
Labels: 💄 style

#108 Feat/90 plan list
  public/icons/checkmark-done.svg
  public/icons/fi-sr-bookmark.svg
  public/icons/fi-sr-car.svg
  public/icons/location-white.svg
  src/app/(provider)/(root)/my/bookmarks/_components/BookmarkCard.tsx
  src/app/(provider)/(root)/my/bookmarks/page.tsx
  src/app/(provider)/(root)/plan/[planId]/page.tsx
  src/app/(provider)/(root)/plan/[planId]/route/_components/RouteCard.tsx
  src/app/(provider)/(root)/plan/_components/CreateButton.tsx
  src/app/(provider)/(root)/plan/_components/CreatePlanButton.tsx
  src/app/(provider)/(root)/plan/_components/CreateScheduleButton.tsx
  src/app/(provider)/(root)/plan/layout.tsx
  src/app/(provider)/(root)/plan/page.tsx
  src/app/layout.tsx
  src/components/Card/RatingIcons.tsx
  src/constants/icon.ts
  src/providers/query.provider.tsx
Labels: 💄 style

#111 dev to main
  next.config.mjs
  public/icons/checkmark-done.svg
  public/icons/fi-sr-bookmark.svg
  public/icons/fi-sr-car.svg
  public/icons/location-white.svg
  src/apis/auth.api.ts
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/my/_components/FooterList.tsx
  src/app/(provider)/(root)/my/_components/MyProfile.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/BookmarkCard.tsx
  src/app/(provider)/(root)/my/bookmarks/page.tsx
  src/app/(provider)/(root)/onboard/_components/OnBoard/OnBoard.tsx
  src/app/(provider)/(root)/plan/[planId]/page.tsx
  src/app/(provider)/(root)/plan/[planId]/route/_components/RouteCard.tsx
  src/app/(provider)/(root)/plan/_components/CreateButton.tsx
  src/app/(provider)/(root)/plan/_components/CreatePlanButton.tsx
  src/app/(provider)/(root)/plan/_components/CreateScheduleButton.tsx
  src/app/(provider)/(root)/plan/layout.tsx
  src/app/(provider)/(root)/plan/page.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/[areaType]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/(provider)/(root)/recommend/page.tsx
  src/app/api/auth/logout/route.ts
  src/app/api/auth/update/route.ts
  src/app/api/auth/user/route.ts
  src/app/layout.tsx
  src/components/Card/RatingIcons.tsx
  src/constants/icon.ts
  src/hooks/useAuthFlow.ts
  src/middleware.ts
  src/providers/query.provider.tsx
Labels: 🚩end

#124 chore: 디자인 시스템(컬러) 추가
  public/icons/arrow-right-short-sm-black.svg
  public/icons/arrows/arrow-down-short-md-black.svg
  public/icons/arrows/arrow-down-short-sm-black.svg
  public/icons/arrows/arrow-left-short-md-black.svg
  public/icons/arrows/arrow-left-short-sm-black.svg
  public/icons/arrows/arrow-right-short-md-black.svg
  public/icons/arrows/arrow-right-short-sm-black.svg
  public/icons/arrows/arrow-up-down-black.svg
  public/icons/arrows/arrow-up-left-black.svg
  public/icons/arrows/arrow-up-long-black.svg
  public/icons/arrows/arrow-up-right-black.svg
  public/icons/arrows/arrow-up-short-md-black.svg
  public/icons/arrows/arrow-up-short-sm-black.svg
  src/app/(provider)/(root)/_components/CategorySection.tsx
  src/app/(provider)/(root)/_components/Home.tsx
  src/components/Drawer/Drawer.tsx
  src/constants/color.ts
  src/constants/icon.ts
  src/constants/icons/arrows.ts
  styles/theme/colors.ts
  tailwind.config.ts
Labels: 💄 style, 🔧 chore

#125 Feat/104 create plan flow
  public/icons/person-add.svg
  src/apis/plan.api.ts
  src/app/(provider)/(root)/account/_components/Badge.tsx
  src/app/(provider)/(root)/account/page.tsx
  src/app/(provider)/(root)/onboard/_components/OnBoard/OnBoard.tsx
  src/app/(provider)/(root)/onboard/_components/SelectButton/SelectButton.tsx
  src/app/(provider)/(root)/onboard/_components/SelectContainer/SelectContainer.tsx
  src/app/(provider)/(root)/onboard/_components/SelectForm/SelectForm.tsx
  src/app/(provider)/(root)/plan/create/_components/Input.tsx
  src/app/(provider)/(root)/plan/create/_components/NewPlanBase.tsx
  src/app/(provider)/(root)/plan/create/_components/NewPlanStyle.tsx
  src/app/(provider)/(root)/plan/create/page.tsx
  src/app/api/plan/route.ts
  src/components/TravelStyle/TravelStyle.tsx
  src/components/TravelStyle/index.ts
  src/constants/icon.ts
  src/types/plan.ts
Labels: 📌 feat, 🎉 add

#129 Feat/126 plan design
  public/icons/bookmark.svg
  public/icons/car.svg
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/plan/[planId]/route/_components/RouteCard.tsx
  src/app/(provider)/(root)/plan/_components/CreateButton.tsx
  src/app/(provider)/(root)/plan/_components/CreatePlanButton.tsx
  src/app/(provider)/(root)/plan/_components/CreateScheduleButton.tsx
  src/app/(provider)/(root)/plan/_components/Plan.tsx
  src/app/(provider)/(root)/plan/_components/PlanList.tsx
  src/app/(provider)/(root)/plan/_components/Suggestion.tsx
  src/app/(provider)/(root)/plan/_components/icons/IconAdd.tsx
  src/app/(provider)/(root)/plan/_components/icons/IconBookmark.tsx
  src/app/(provider)/(root)/plan/_components/icons/IconCar.tsx
  src/app/(provider)/(root)/plan/_components/icons/IconCheck.tsx
  src/app/(provider)/(root)/plan/_components/icons/IconPin.tsx
  src/app/(provider)/(root)/plan/create/_components/NewPlanBase.tsx
  src/app/(provider)/(root)/plan/page.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/CardImgFrame.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/DetailCard.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/ReviewCard.tsx
  src/app/(provider)/(root)/recommend/_components/CountryPage/InstroSlider.tsx
  src/app/(provider)/(root)/recommend/_components/MainTour/MainTourItem.tsx
  src/app/(provider)/(root)/recommend/_components/VanilaImgFram.tsx
  src/app/(provider)/(root)/recommend/page.tsx
  src/app/layout.tsx
  src/components/Card/CardType.tsx
  src/components/Frame/ImageFrame.tsx
  src/components/Frame/Profile.tsx
  src/components/commons/Header/Header.tsx
  src/constants/icon.ts
  src/stores/modal.store.ts
  src/utils/DateUtil.ts
  tailwind.config.ts
Labels: 💄 style, 🔧 chore

#133 Feat/126 plan design
  public/icons/share.svg
  src/apis/plan.api.ts
  src/app/(provider)/(root)/plan/[planId]/route/_components/Map.tsx
  src/app/(provider)/(root)/plan/[planId]/route/_components/RouteCard.tsx
  src/app/(provider)/(root)/plan/[planId]/route/page.tsx
  src/app/(provider)/(root)/plan/_components/Color.ts
  src/app/(provider)/(root)/plan/_components/icons/IconPin.tsx
  src/app/(provider)/(root)/plan/create/_components/NewPlanBase.tsx
  src/app/(provider)/(root)/plan/create/page.tsx
  src/components/commons/TagButton/TagButton.tsx
  src/components/commons/TagList/SlideTagList.tsx
  src/constants/icon.ts
  src/utils/DateUtil.ts
Labels: 💄 style

#138 dev to main
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/constants/icon.ts
Labels: 🚩end

#177 Feat : #175 탭 컴포넌트 디자인 수정
  package-lock.json
  package.json
  public/icons/add-bold.svg
  public/icons/share-white.svg
  src/apis/area.api.ts
  src/app/(provider)/(root)/recommend/_components/AreaPage/UnderBar.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/DateList.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/PlanItem.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetImages.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetInput.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetRating.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/CardImgFrame.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/DetailCard.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/globals.css
  src/components/Tab/Tab.tsx
  src/constants/icon.ts
  src/hooks/useTab.tsx
  src/utils/adjustDate.ts
  tailwind.config.ts
Labels: 💄 style

#178 dev to main
  package-lock.json
  package.json
  public/icons/add-bold.svg
  public/icons/share-white.svg
  src/apis/area.api.ts
  src/app/(provider)/(root)/recommend/_components/AreaPage/UnderBar.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/DateList.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/PlanItem.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetImages.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetInput.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetRating.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/CardImgFrame.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/DetailCard.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/(root)/recommend/area/[id]/page.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/globals.css
  src/components/Tab/Tab.tsx
  src/constants/icon.ts
  src/hooks/useTab.tsx
  src/utils/adjustDate.ts
  tailwind.config.ts
Labels: 🚩end

#176 chore: 소셜로그인 온보딩 리다이렉트 시도
  public/icon/calculator.png
  public/icons/calculator.svg
  public/icons/calendar-black.svg
  public/icons/edit-line.svg
  public/icons/map.svg
  public/icons/star-black.svg
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/(auth)/login/_components/AuthForm/AuthForm.tsx
  src/app/(provider)/(root)/(auth)/login/page.tsx
  src/app/(provider)/(root)/my/_components/FooterList.tsx
  src/app/(provider)/(root)/my/_components/MyMenu.tsx
  src/app/(provider)/(root)/my/_components/MyPageSection.tsx
  src/app/(provider)/(root)/my/_components/MyProfile.tsx
  src/app/(provider)/(root)/my/_components/MySchedule.tsx
  src/app/(provider)/(root)/my/page.tsx
  src/app/api/auth/callback/route.ts
  src/constants/icon.ts
  src/hooks/useAuthFlow.ts
Labels: ✨ update, 🛠️ fix

#182 Feat : #179 #180 로그인 모달 및 도시,나라 상세 페이지 상단 카드 디자인 수정
  public/arch-mask.svg
  src/app/(provider)/(root)/recommend/_components/AreaPage/ReviewSummary.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/UnderBar.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/BookMarkCard.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/DetailCard.tsx
  src/app/globals.css
  src/components/Modal/Modal.tsx
  src/components/Tab/Tab.tsx
  src/stores/modal.store.ts
Labels: 📌 feat, 💄 style

#195 Feat/127 my bookmarks
  src/apis/bookmark.api.ts
  src/apis/plan.api.ts
  src/app/(provider)/(root)/my/bookmarks/_components/AddToPlanButton.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/BookmarkButton.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/BookmarkCard.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/MyBookmarkList.tsx
  src/app/(provider)/(root)/my/bookmarks/page.tsx
  src/app/(provider)/(root)/plan/[planId]/page.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheet.tsx
  src/app/(provider)/(root)/plan/_components/CreateButton.tsx
  src/app/(provider)/(root)/plan/_components/CreatePlanButton.tsx
  src/app/(provider)/(root)/plan/_components/PlanList.tsx
  src/app/(provider)/(root)/plan/create/_components/NewPlanBase.tsx
  src/app/(provider)/(root)/plan/create/page.tsx
  src/app/(provider)/(root)/plan/page.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheetTitle.tsx
  src/app/api/area/plan/route.ts
  src/app/api/auth/AuthUtil.ts
  src/app/api/bookmark/route.ts
  src/app/api/plan/[planId]/route.ts
  src/app/api/plan/[planId]/schedule/route.ts
  src/app/api/plan/route.ts
  src/app/globals.css
  src/constants/tabs.ts
  src/hooks/useBookmark.ts
  src/types/Recommend.ts
  src/types/plan.ts
  src/utils/DateUtil.ts
  src/utils/PlanUtil.ts
Labels: 🛠️ fix

#193 feat: svgr 컴포넌트 제작
  next.config.mjs
  package-lock.json
  package.json
  public/icons/arrows/angle-down.svg
  public/logo.png
  public/logo.svg
  src/app/(provider)/(root)/_components/Footer.tsx
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/_components/MyTrip.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/BookMarkCard.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/layout.tsx
  src/assets/icons/arrow-right.svg
  src/assets/icons/hamburger.svg
  src/assets/icons/search.svg
  src/components/Drawer/Category.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/commons/Header/Header.tsx
  src/components/commons/SvgIcon/SvgIcon.tsx
  src/components/commons/SvgIcon/index.ts
  src/types/SvgIcon.ts
  svgr.d.ts
  tsconfig.json
Labels: 📌 feat

#208 dev to main
  src/app/(provider)/(root)/plan/[planId]/page.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheet.tsx
  src/app/(provider)/(root)/plan/_components/ScheduleList.tsx
  src/app/api/plan/[planId]/schedule/route.ts
  src/stores/schedule.store.ts
  src/types/plan.ts
Labels: 🚩end

#215 feat : #214 북마크 optimistic update 적용
  public/arch-mask.svg
  public/icons/add-black.svg
  src/apis/bookmark.api.ts
  src/apis/review.api.ts
  src/app/(provider)/(root)/my/bookmarks/_components/BookmarkButton.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/MyBookmarkList.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/AreaReviewCard.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/ReviewSummary.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/UnderBar.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheetInput.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheetRating.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetRating.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/BookMarkCard.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/app/api/bookmark/route.ts
  src/app/api/review/route.ts
  src/components/Card/RatingIcons.tsx
  src/components/Card/SingleRatingIcon.tsx
  src/components/Modal/Modal.tsx
  src/components/commons/Header/Header.tsx
  src/constants/icon.ts
  src/hooks/useBookmark.ts
  src/stores/modal.store.ts
  src/types/Recommend.ts
Labels: 📌 feat, 🛠️ fix

#216 Bugfix/213 plans
  public/icons/ellipsis.svg
  public/icons/map-white.svg
  src/app/(provider)/(root)/my/bookmarks/_components/MyBookmarkList.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/SuggestArea.tsx
  src/app/(provider)/(root)/plan/[planId]/page.tsx
  src/app/(provider)/(root)/plan/_components/CreateButton.tsx
  src/app/(provider)/(root)/plan/_components/CreateScheduleButton.tsx
  src/app/(provider)/(root)/plan/_components/DayMenu.tsx
  src/app/(provider)/(root)/plan/_components/ScheduleList.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/assets/icons/map-route.svg
  src/components/Layout/MainLayout.tsx
  src/components/commons/Header/Header.tsx
  src/constants/icon.ts
  src/stores/schedule.store.ts
Labels: ✨ update, 🛠️ fix, 🔧 chore

#217 dev to main
  public/arch-mask.svg
  public/icons/add-black.svg
  public/icons/ellipsis.svg
  public/icons/map-white.svg
  src/apis/bookmark.api.ts
  src/apis/review.api.ts
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/(auth)/login/_components/Login/Login.tsx
  src/app/(provider)/(root)/(auth)/login/_components/ProgressBar/ProgressBar.tsx
  src/app/(provider)/(root)/my/_components/MyMenu.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/BookmarkButton.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/MyBookmarkList.tsx
  src/app/(provider)/(root)/my/bookmarks/_components/SuggestArea.tsx
  src/app/(provider)/(root)/plan/[planId]/page.tsx
  src/app/(provider)/(root)/plan/_components/CreateButton.tsx
  src/app/(provider)/(root)/plan/_components/CreateScheduleButton.tsx
  src/app/(provider)/(root)/plan/_components/DayMenu.tsx
  src/app/(provider)/(root)/plan/_components/ScheduleList.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/AreaReviewCard.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/ReviewSummary.tsx
  src/app/(provider)/(root)/recommend/_components/AreaPage/UnderBar.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheetInput.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheetRating.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/EditSheet/ReviewSheet/EditBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewSheet/ReviewBottomSheetRating.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/BookMarkCard.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/(root)/recommend/city/[id]/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/detail/page.tsx
  src/app/(provider)/(root)/recommend/country/[id]/page.tsx
  src/app/api/bookmark/route.ts
  src/app/api/review/route.ts
  src/assets/icons/map-route.svg
  src/components/Card/RatingIcons.tsx
  src/components/Card/SingleRatingIcon.tsx
  src/components/Layout/MainLayout.tsx
  src/components/Modal/Modal.tsx
  src/components/commons/Header/Header.tsx
  src/constants/icon.ts
  src/hooks/useAuthFlow.ts
  src/hooks/useBookmark.ts
  src/stores/modal.store.ts
  src/stores/schedule.store.ts
  src/stores/step.store.ts
  src/types/Recommend.ts
Labels: 🚩end

#224 update: drawer 디자인
  public/drawer/drawer-bookmark.svg
  public/logo.svg
  public/travelstory-logo.png
  src/apis/country.api.ts
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/_components/LeftCardSection.tsx
  src/app/(provider)/(root)/_components/MyTrip.tsx
  src/app/(provider)/(root)/plan/[planId]/ScheduleList.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/api/country/drawer/route.ts
  src/app/layout.tsx
  src/assets/icons/angle-right.svg
  src/assets/icons/bookmark.svg
  src/components/Drawer/BackDrop.tsx
  src/components/Drawer/Category.tsx
  src/components/Drawer/CategoryList.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/DrawerMyProfile.tsx
  src/components/Drawer/MyTripPlanner.tsx
  src/components/Drawer/TripList.tsx
  src/components/Slider/ArchCardSlider.tsx
  src/components/commons/SvgIcon/SvgIcon.tsx
  tailwind.config.ts
Labels: ✨ update, 🛠️ fix, 💄 style

#228 hotfix: 메인 페이지 avatar 아이콘 추가
  public/icons/search-black.png
  src/app/(provider)/(root)/_components/Home.tsx
Labels: 🚨 hotfix

#230 feat: #169 온보딩 flow 완성
  public/onboard/amphora.png
  public/onboard/cherry-blossom.png
  public/onboard/child.png
  public/onboard/cityscape.png
  public/onboard/classical-building.png
  public/onboard/desert-island.png
  public/onboard/dog-face.png
  public/onboard/fallen-leaf.png
  public/onboard/fork-knife-plate.png
  public/onboard/gem-stone.png
  public/onboard/globe-asia.png
  public/onboard/globe-australia.png
  public/onboard/globe-europe.png
  public/onboard/globe-north-america.png
  public/onboard/globe-south-america.png
  public/onboard/highfive.png
  public/onboard/house-garden.png
  public/onboard/house.png
  public/onboard/human.png
  public/onboard/national-park.png
  public/onboard/old-woman.png
  public/onboard/ring.png
  public/onboard/snowman.png
  public/onboard/surfing.png
  public/onboard/tropical-drink.png
  public/onboard/violin.png
  src/app/(provider)/(root)/my/_components/MyMenu.tsx
  src/app/(provider)/(root)/my/_components/MyProfile.tsx
  src/app/(provider)/(root)/onboard/_components/BoardContainer.tsx
  src/app/(provider)/(root)/onboard/_components/Continent.tsx
  src/app/(provider)/(root)/onboard/_components/OnBoard/OnBoard.tsx
  src/app/(provider)/(root)/onboard/_components/ProgressBar.tsx
  src/app/(provider)/(root)/onboard/_components/SelectButton/ContinentButton.tsx
  src/app/(provider)/(root)/onboard/_components/TravelMate.tsx
  src/app/(provider)/(root)/onboard/_components/TravelType.tsx
  src/assets/icons/cancel.svg
  src/stores/onboard.store.ts
Labels: 📌 feat, 💄 style

#227 update: 검색결과 UI 변경
  public/category/accommodation.svg
  public/category/place.svg
  public/category/restaurant.svg
  public/category/shop.svg
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/(provider)/(root)/search/page.tsx
  src/assets/icons/slider.svg
  src/assets/icons/x.svg
  src/components/Card/AreaTagCard.tsx
  src/components/CountryButton/CountryButton.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/commons/SvgIcon/SvgIcon.tsx
  src/constants/category.ts
  src/types/Card.ts
  src/types/SvgIcon.ts
  src/utils/getKrCategory.ts
  tailwind.config.ts
Labels: ✨ update, 💄 style

#234 Feat/207 plan route
  src/apis/plan.api.ts
  src/app/(provider)/(root)/plan/[planId]/route/_components/RouteCard.tsx
  src/app/(provider)/(root)/plan/[planId]/route/page.tsx
  src/app/api/plan/[planId]/route.ts
  src/types/ApiResponse.ts
  src/types/plan.ts
  src/utils/DateUtil.ts
Labels: 📌 feat, 💄 style

#243 update: 검색 필터 추가 및 svgr 컴포넌트 수정
  package-lock.json
  package.json
  public/icons/search-black.png
  src/apis/area.api.ts
  src/app/(provider)/(root)/_components/Home.tsx
  src/app/(provider)/(root)/search/_components/Button/FilterButton.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/InitialSearchView.tsx
  src/app/(provider)/(root)/search/_components/SearchFilter.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/(provider)/(root)/search/page.tsx
  src/app/api/area/search/route.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/Tab/Tab.tsx
  src/components/commons/CountryButton/CountryButton.stories.ts
  src/components/commons/CountryButton/CountryButton.tsx
  src/components/commons/CountryButton/index.ts
  src/components/commons/SubmitButton/SubmitButton.tsx
  src/components/commons/SvgIcon/SvgIcon.tsx
  src/constants/tabs.ts
  src/stores/drawer.store.ts
  src/stores/searchFilter.store.ts
  src/types/SvgIcon.ts
  tailwind.config.ts
Labels: ✨ update

#240 Feat/animation
  src/apis/area.api.ts
  src/apis/bookmark.api.ts
  src/apis/city.api.ts
  src/apis/country.api.ts
  src/apis/review.api.ts
  src/app/(provider)/(root)/recommend/_components/BottomSheet/AddAreaSheet/AddBottomSheetTitle.tsx
  src/app/(provider)/(root)/recommend/_components/BottomSheet/ReviewBottomSheet.tsx
  src/app/(provider)/(root)/recommend/_components/Cards/AreaCard.tsx
  src/app/(provider)/(root)/recommend/_components/CountryPage/CityImage.tsx
  src/app/globals.css
  src/components/Drawer/DrawerMyProfile.tsx
  src/components/DropdownMenu/ReviewDropdownMenu.tsx
Labels: 💄 style

#247 Feat: #189 마이페이지 프로필 수정, 최신 일정 연결
  src/apis/auth.api.ts
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/(auth)/login/_components/ProgressBar/ProgressBar.tsx
  src/app/(provider)/(root)/my/_components/FooterList.tsx
  src/app/(provider)/(root)/my/_components/MyMenu.tsx
  src/app/(provider)/(root)/my/_components/MyPageSection.tsx
  src/app/(provider)/(root)/my/_components/MyProfile.tsx
  src/app/(provider)/(root)/my/_components/MySchedule.tsx
  src/app/(provider)/(root)/my/page.tsx
  src/app/(provider)/(root)/onboard/_components/BoardContainer.tsx
  src/app/api/auth/update/profile/route.ts
  src/assets/icons/edit.svg
  src/assets/icons/picture.svg
  src/components/commons/Header/Header.tsx
  src/stores/auth.store.ts
Labels: ✨ update

#246 Feat/205 schedule update
  src/apis/plan.api.ts
  src/app/(provider)/(root)/plan/[planId]/ScheduleList.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheet.tsx
  src/app/(provider)/(root)/plan/_components/CheckList.tsx
  src/app/(provider)/(root)/plan/_components/Memo.tsx
  src/app/(provider)/(root)/plan/_components/MoveSchedule.tsx
  src/app/(provider)/(root)/plan/_components/Schedule.tsx
  src/app/(provider)/(root)/plan/_components/ScheduleList.tsx
  src/app/(provider)/(root)/plan/_components/getInsertData.ts
  src/app/(provider)/(root)/plan/create/_components/NewPlanBase.tsx
  src/app/api/plan/[planId]/PlanChildTable.ts
  src/app/api/plan/[planId]/route.ts
  src/app/api/plan/[planId]/schedule/route.ts
  src/stores/schedule.store.ts
  src/types/plan.ts
  src/utils/PlanUtil.ts
Labels: ✨ update

#250 update: 검색 페이지 디테일 작업
  src/app/(provider)/(root)/_components/ArchCard.tsx
  src/app/(provider)/(root)/_components/LeftCardSection.tsx
  src/app/(provider)/(root)/_hook/useGetData.ts
  src/app/(provider)/(root)/search/_components/Button/FilterButton.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/InitialSearchView.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/(provider)/(root)/search/page.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/commons/CountryButton/CountryButton.tsx
Labels: ✨ update

#253 스케줄, 이미지 업로더 추가
  src/app/(provider)/(root)/plan/_components/BottomSheet.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetImages.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetInput.tsx
  src/app/(provider)/(root)/plan/_components/MoveSchedule.tsx
  src/app/(provider)/(root)/plan/_components/getInsertData.ts
  src/components/ImageUploader/ImageUploader.tsx
  src/components/ImageUploader/index.ts
  src/components/ImageUploader/upload.ts
Labels: 📌 feat

#257 로그인 화면, header left 뒤로가기 아이콘 나오도록
  public/icons/arrow-back-black.png
  public/icons/arrow-back.svg
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/my/_components/MyPageSection.tsx
  src/components/commons/Header/Header.tsx
  src/constants/icon.ts
Labels: 🔧 chore

#263 dev to main
  package-lock.json
  package.json
  public/icons/arrow-back-black.png
  public/icons/arrow-back.svg
  public/icons/arrow-down-black.png
  src/apis/plan.api.ts
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/my/_components/MyPageSection.tsx
  src/app/(provider)/(root)/my/reviews/_components/MyReviewList.tsx
  src/app/(provider)/(root)/my/reviews/_components/MyReviewSection.tsx
  src/app/(provider)/(root)/my/reviews/_components/ReviewCard.tsx
  src/app/(provider)/(root)/my/reviews/page.tsx
  src/app/(provider)/(root)/onboard/_components/BoardContainer.tsx
  src/app/(provider)/(root)/onboard/_components/TravelMate.tsx
  src/app/(provider)/(root)/onboard/_components/TravelType.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheet.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetImages.tsx
  src/app/(provider)/(root)/plan/_components/BottomSheetInput.tsx
  src/app/(provider)/(root)/plan/_components/Loading.tsx
  src/app/(provider)/(root)/plan/_components/MoveSchedule.tsx
  src/app/(provider)/(root)/plan/_components/Plan.tsx
  src/app/(provider)/(root)/plan/_components/PlanEllipsisMenu.tsx
  src/app/(provider)/(root)/plan/_components/PlanList.tsx
  src/app/(provider)/(root)/plan/_components/getInsertData.ts
  src/app/(provider)/(root)/plan/page.tsx
  src/app/(provider)/layout.tsx
  src/app/api/plan/[planId]/route.ts
  src/app/api/review/[id]/route.ts
  src/app/layout.tsx
  src/assets/icons/arrow-down.svg
  src/assets/icons/ellipsis.svg
  src/components/ImageUploader/ImageUploader.tsx
  src/components/ImageUploader/index.ts
  src/components/ImageUploader/upload.ts
  src/components/commons/Header/Header.tsx
  src/constants/icon.ts
  src/constants/onboard.ts
  src/contexts/index.ts
  src/contexts/overlay.context.tsx
  src/hooks/useTab.tsx
  src/stores/plan.store.ts
  src/types/Recommend.ts
  tailwind.config.ts
Labels: 📌 feat

#256 feat: #236 최근 검색어 기능 완료
  package.json
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/(auth)/login/_components/ProgressBar/ProgressBar.tsx
  src/app/(provider)/(root)/my/_components/FooterList.tsx
  src/app/(provider)/(root)/my/_components/MyPageSection.tsx
  src/app/(provider)/(root)/my/_components/MyProfile.tsx
  src/app/(provider)/(root)/my/_components/MySchedule.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/InitialSearchView.tsx
  src/app/(provider)/(root)/search/_components/RecentArea.tsx
  src/app/(provider)/(root)/search/_components/RecentSearch.tsx
  src/app/(provider)/layout.tsx
  src/components/SearchBar/SearchBar.tsx
  src/hooks/useAuthFlow.ts
  src/stores/recent.store.ts
  src/types/supabase.ts
  src/utils/searchDate.ts
Labels: 📌 feat

#266 update: 검색결과 더보기 기능
  package-lock.json
  src/apis/area.api.ts
  src/app/(provider)/(root)/search/_components/ClientSearch.tsx
  src/app/(provider)/(root)/search/_components/SearchResultView.tsx
  src/app/api/area/city/allCategory/route.ts
  src/app/api/area/search/route.ts
  src/components/SearchBar/SearchBar.tsx
  src/types/search.ts
Labels: ✨ update

#275 style: #274 로그인 데탑 디자인
  src/app/(provider)/(root)/(auth)/login/_components/AuthContainer/AuthContainer.tsx
  src/app/(provider)/(root)/(auth)/login/_components/AuthForm/AuthForm.tsx
  src/app/(provider)/(root)/(auth)/login/_components/Login/Login.tsx
  src/app/(provider)/(root)/(auth)/login/_components/ProgressBar/ProgressBar.tsx
  src/app/(provider)/(root)/recommend/_components/Pages/AreaDetailCSRPage.tsx
  src/app/(provider)/layout.tsx
  src/assets/icons/kakao-talk.svg
  src/components/Layout/MainLayout.tsx
  src/components/commons/Footer/Footer.tsx
  src/components/commons/Header/Header.tsx
  src/components/commons/Header/LgHeader.tsx
  src/components/commons/TagList/PrimaryTagList.tsx
  tailwind.config.ts
Labels: 💄 style

#292 fix: footer 영역 넓히기, 검색바 크기 조정, 최근 본 장소 카드 크기 조정
  src/app/(provider)/(root)/_components/Footer.tsx
  src/app/(provider)/(root)/onboard/_components/OnBoard/OnBoard.tsx
  src/app/(provider)/(root)/search/_components/RecentArea.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/commons/Footer/Footer.tsx
  src/components/commons/Header/LgHeader.tsx
Labels: ✨ update, 🛠️ fix
